#!/usr/bin/env python

import os
import yaml


PATH_DATA_PROCESSED = os.path.join('bld', 'out', 'data_processed')


def build(ctx):

    # Collect keys of Poloniex data
    with open(os.path.join('src', 'data_collection', 'Poloniex',
                           'poloniex_config.yml'), 'r') as file:
        polo_config = yaml.load(file.read())

    # Run chart data preprocessing
    for key in polo_config.keys():

        ctx(
            features='run_py_script',
            source='poloniex_chart_data.py',
            deps=[
                ctx.path_to(
                    ctx, 'IN_DATA_PREPROCESSING', 'data_preprocessing.yml'),
                ctx.path_to(
                    ctx, 'OUT_DATA_RAW', '{}_chart_data.csv'.format(key)),
            ],
            target=[
                ctx.path_to(
                    ctx, 'OUT_DATA_PROCESSED', '{}_chart_data.p.lzma'
                    .format(key)),
            ],
            append=key,
            name='poloniex_{}_chart_data'.format(key)
        )

    # Run trade history preprocessing
    for key in polo_config.keys():

        ctx(
            features='run_py_script',
            source='poloniex_trade_history.py',
            deps=[
                ctx.path_to(
                    ctx, 'IN_DATA_PREPROCESSING', 'data_preprocessing.yml'),
                ctx.path_to(
                    ctx, 'OUT_DATA_RAW', '{}_trade_history.csv'.format(key)),
            ],
            target=[
                ctx.path_to(
                    ctx, 'OUT_DATA_PROCESSED',
                    '{}_trade_history.p.lzma'.format(key)),
            ],
            append=key,
            name='poloniex_{}_trade_history'.format(key)
        )

    # Merge depends on all previous processed data
    ctx.add_group()

    for key in polo_config.keys():

        ctx(
            features='run_py_script',
            source='poloniex_merge.py',
            deps=[
                ctx.path_to(
                    ctx, 'OUT_DATA_PROCESSED', '{}_chart_data.p.lzma'
                    .format(key)),
                ctx.path_to(
                    ctx, 'OUT_DATA_PROCESSED',
                    '{}_trade_history.p.lzma'.format(key))
            ],
            target=[
                ctx.path_to(
                    ctx, 'OUT_DATA_PROCESSED', '{}.p.lzma'.format(key)),
            ],
            append=key,
            name='poloniex_merge_{}'.format(key)
        )

    # Stanford twitter sentiment corpus
    ctx(
        features='run_py_script',
        source='twitter_stanford.py',
        deps=ctx.path_to(
            ctx, 'OUT_DATA_RAW', 'stanford_twitter_sentiment_corpus.csv'),
        target=ctx.path_to(
            ctx, 'OUT_DATA_PROCESSED', 'twitter_stanford.p.lzma'),
        name='twitter_stanford'
    )
