# Twitter configuration file

# This file specifies for which search queries a data collection is performed.
# Each dictionary specifies one search query.

# Note that, the key of the dictionary is used as a filename

# Example:
# poloniex:
#   username: barackobama (drop @)
#   since: '2017-01-01' ('YYYY-MM-DD')
#   until: '2017-01-31' ('YYYY-MM-DD')
#   querysearch: "valentine"
#   toptweets: True
#   maxtweets: 100 (all if nothing)
#   near: Bonn,Germany
#   within: 30km (15mi is also possible)

potcoin:
  since: '2014-01-01'
  querysearch: 'potcoin'
  toptweets: ''
  maxtweets: 100

bitcoin:
  since: '2014-01-01'
  querysearch: 'bitcoin'
  toptweets: ''
  maxtweets: 100