dependencies:
- alabaster=0.7.9=py35_0
- babel=2.3.4=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- decorator=4.0.10=py35_0
- docutils=0.12=py35_2
- entrypoints=0.2.2=py35_0
- expat=2.1.0=0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- imagesize=0.7.1=py35_0
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_1
- jpeg=8d=2
- jsonschema=2.5.1=py35_0
- jupyter_client=4.4.0=py35_0
- jupyter_core=4.2.0=py35_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libxcb=1.12=1
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- mistune=0.7.3=py35_0
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- notebook=4.2.3=py35_0
- numpy=1.11.2=py35_0
- openblas=0.2.14=4
- openssl=1.0.2j=0
- pandas=0.19.1=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_0
- prompt_toolkit=1.0.8=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.7=py35_0
- pyzmq=16.0.0=py35_0
- qt=5.6.0=1
- readline=6.2=2
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.4.8=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - cloud-sptheme==1.7.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-core==4.2.0
  - latexcodec==1.0.1
  - oset==0.1.3
  - prompt-toolkit==1.0.8
  - pybtex==0.19
  - pybtex-docutils==0.2.1
  - pyyaml==3.11
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-bibtex==0.3.3
