# Poloniex configuration file

# This file specifies for which exchange rates a data collection is performed.
# A list of possible pairs can be found here:

#     https://poloniex.com/public?command=return24hVolume

BTC_POT:
  START_DATE: 1388530800  # Foundation of Poloniex
  PERIOD: 7776000  # three months