#!/usr/bin/env python


def build(ctx):

    ctx(
        features='run_py_script',
        source='schelling.py',
        deps=[
            ctx.path_to(ctx, 'OUT_DATA_PROCESSED', 'initial_locations.csv'),
        ],
        target=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'schelling_{}.pickle'.format(model)),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'log', 'schelling_{}.log'.format(model))
        ],
        append=model,
        name='schelling_{}'.format(model)
    )