#!/usr/bin/env python3

import yaml
import os


PATH_MA_CONFIG = os.path.join('src', 'analysis', 'ma.yml')


def build(ctx):

    with open(PATH_MA_CONFIG) as file:
        ma_conf = yaml.load(file.read())

    for key in ma_conf:
        for fast, slow in ma_conf[key]:

            ctx(
                features='run_py_script',
                source=ctx.path_to(ctx, 'IN_ANALYSIS', 'ma.py'),
                deps=[
                    ctx.path_to(
                        ctx, 'IN_PREDICTION_MODELS', 'moving_average.py'),
                    ctx.path_to(
                        ctx, 'IN_ANALYSIS', 'ma.yml'),
                    ctx.path_to(
                        ctx, 'OUT_DATA_PROCESSED', '{}_chart_data.p.lzma'
                        .format(key))
                ],
                target=[
                    ctx.path_to(
                        ctx, 'OUT_FIGURES', 'ma_signal_regime_{}_{}_{}.png'
                        .format(key, fast / 12 / 24, slow / 12 / 24)),
                    ctx.path_to(
                        ctx, 'OUT_FIGURES', 'ma_price_{}_{}_{}.png'
                        .format(key, fast / 12 / 24, slow / 12 / 24))
                ],
                append=[key, str(fast), str(slow)],
                name='analysis',
            )
