#!/usr/bin/env python3


def build(ctx):
    # # Tests
    ctx(
        features='run_py_script',
        source='test_financial_indicators.py',
        deps=ctx.path_to(
            ctx, 'IN_TRANSFORMERS', 'financial_indicators.py')
    )
